
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/koltunov_db
    username: koltunov
    password: 123
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always

logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init: DEBUG
